{
    config, lib, pkgs,
    ...
}: let
    cfg = config.services.homelab-backup;

    # Crafty's bind-mount root.  Kept in sync with
    # modules/services/minecraft/crafty.nix by hand -- that module hardcodes
    # the same literal, so there is no option to derive it from.
    craftyDataDir = "/var/lib/Minecraft/docker";

    # Every agent's home, DERIVED from the agents set so adding an agent to
    # hosts/homeserver/hermes_profiles.nix automatically gets it backed up
    # with no edit here.  Reading only the attribute *names* is what keeps
    # this from recursing.
    agentNames = lib.attrNames config.services.hermes-agents.agents;
    hermesDirs = map (n: "/home/${n}/.hermes") agentNames;

    # SQLite databases (state.db, kanban.db) are written live by a running
    # agent.  Copying the .db file while a -wal exists yields a snapshot that
    # may not restore, so each one is checkpointed into a staging directory
    # first and the live files are excluded from the snapshot instead.
    stagingDir = "/var/lib/hermes-db-snapshots";

    snapshotDbs = pkgs.writeShellScript "hermes-db-snapshot" ''
        set -u
        PATH=${lib.makeBinPath [ pkgs.sqlite pkgs.coreutils pkgs.findutils ]}

        rm -rf ${stagingDir}
        install -d -m 0700 ${stagingDir}

        ${lib.concatMapStringsSep "\n" (name: ''
          src=/home/${name}/.hermes
          dst=${stagingDir}/${name}
          if [ -d "$src" ]; then
            install -d -m 0700 "$dst"
            find "$src" -maxdepth 1 -type f -name '*.db' -print0 |
              while IFS= read -r -d ''' db; do
                base=$(basename "$db")
                if ! sqlite3 -readonly "$db" ".backup '$dst/$base'"; then
                  echo "warn: sqlite checkpoint failed for $db, copying raw" >&2
                  cp -a "$db" "$dst/$base" || true
                  for side in -wal -shm; do
                    [ -e "$db$side" ] && cp -a "$db$side" "$dst/$base$side" || true
                  done
                fi
              done
          fi
        '') agentNames}
    '';

    commonExclude = [
        # Regenerable caches and logs -- large, worthless in a restore.
        "**/.hermes/cache"
        "**/.hermes/logs"
        "**/.hermes/lsp"
        "**/.hermes/audio_cache"
        "**/.hermes/models_dev_cache.json"
        "**/node_modules"
        "**/__pycache__"
        # Live SQLite: replaced by the consistent copies in stagingDir.
        "**/.hermes/*.db"
        "**/.hermes/*.db-wal"
        "**/.hermes/*.db-shm"
    ];

    mkJob = name: paths: extra: lib.mkMerge [
        {
            repository = cfg.repository;
            passwordFile = cfg.passwordFile;
            inherit paths;
            initialize = true;
            exclude = commonExclude;
            extraBackupArgs = [ "--tag" name "--one-file-system" ];
            pruneOpts = cfg.pruneOpts;
            # Verify structural integrity after pruning; a repo that only
            # ever gets written is a repo nobody has proven is restorable.
            checkOpts = [ "--with-cache" ];
            runCheck = true;
            timerConfig = {
                OnCalendar = cfg.onCalendar;
                Persistent = true;
                RandomizedDelaySec = "15m";
            };
        }
        extra
    ];
in {
    options.services.homelab-backup = {
        enable = lib.mkEnableOption "nightly restic backups to the local SATA disk";

        repository = lib.mkOption {
            type = lib.types.str;
            default = "/mnt/backup/restic";
            description = ''
                Path of the restic repository.  Must live on a mounted
                filesystem; the units get a RequiresMountsFor on it so a
                missing disk fails the job loudly instead of silently filling
                the root SSD.
            '';
        };

        device = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = "/dev/disk/by-label/backup";
            description = ''
                Block device mounted at `mountPoint`.  Deliberately declared
                here and NOT in hardware-configuration.nix, because that file
                is regenerated by `nixos-generate-config` and would lose the
                entry.  Set to null to manage the mount elsewhere.

                by-label rather than by-uuid so reformatting the disk with
                `mkfs.ext4 -L backup` does not require a config edit.
            '';
        };

        mountPoint = lib.mkOption {
            type = lib.types.str;
            default = "/mnt/backup";
            description = "Where `device` is mounted.";
        };

        passwordFile = lib.mkOption {
            type = lib.types.path;
            example = lib.literalExpression ''config.age.secrets."restic-homeserver".path'';
            description = ''
                File holding the repository password.  Consumed by path, never
                by value -- interpolating it into a Nix string would copy the
                password into the world-readable /nix/store.

                Losing this file makes every snapshot unreadable.  Keep a copy
                off the machine.
            '';
        };

        onCalendar = lib.mkOption {
            type = lib.types.str;
            default = "03:30";
            description = "systemd OnCalendar expression for the nightly run.";
        };

        pruneOpts = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            default = [
                "--keep-daily 7"
                "--keep-weekly 4"
                "--keep-monthly 6"
            ];
            description = "Retention passed to `restic forget --prune`.";
        };
    };

    config = lib.mkIf cfg.enable {
        # mkDefault throughout: if a future `nixos-generate-config` run happens
        # while this disk is mounted, it emits a by-uuid entry for the same
        # mount point.  Without mkDefault that is a "conflicting definitions"
        # build failure; with it, the generated hardware config simply wins.
        fileSystems = lib.mkIf (cfg.device != null) {
            ${cfg.mountPoint} = {
                device = lib.mkDefault cfg.device;
                fsType = lib.mkDefault "ext4";
                # nofail: a dead/absent backup disk must not drop the whole
                # homeserver into emergency mode at boot.  The backup units
                # still fail loudly via RequiresMountsFor below.
                options = lib.mkDefault [ "defaults" "nofail" "noatime" ];
            };
        };

        # restic's NixOS module runs jobs as root by default, which is what we
        # want here: root is the only account that can read every agent's
        # ~/.hermes and the Crafty bind mounts, and the backup must not be
        # readable or deletable by the agents it protects.
        services.restic.backups = {
            crafty = mkJob "crafty" [ craftyDataDir ] { };

            hermes = mkJob "hermes" (hermesDirs ++ [ stagingDir ]) {
                backupPrepareCommand = "${snapshotDbs}";
                # Staging holds decrypted agent state; drop it once captured.
                backupCleanupCommand = "${pkgs.coreutils}/bin/rm -rf ${stagingDir}";
            };
        };

        # Without this the unit happily creates /mnt/backup/restic on the root
        # SSD when the SATA disk is absent, and the "backup" silently lives on
        # the same disk it is meant to survive.
        systemd.services.restic-backups-crafty.unitConfig.RequiresMountsFor = cfg.repository;
        systemd.services.restic-backups-hermes.unitConfig.RequiresMountsFor = cfg.repository;

        environment.systemPackages = [ pkgs.restic ];
    };
}
