{ pkgs, lib, agent, accounts, clientSecretFile, hermesHome, googlePython }:

let
    google = import ./default.nix { inherit lib; };


    # The manifest that defines what the CLI can do for this account. It is used as an input for the google_accounts.py script.

    manifestData = {
        inherit agent clientSecretFile hermesHome;

        redirectUri = "http://localhost:1";

        # The capability table itself travels with the manifest, so the CLI's
        # error messages are derived from the same data Nix validated against
        # and cannot drift from it.
        reference = google.reference;

        accounts = lib.mapAttrs (name: acct: {
            inherit (acct) capabilities address purpose publishing project;
            scopes = google.scopesFor acct.capabilities;
            tokenHome = "${hermesHome}/google/${name}";
            tokenPath = "${hermesHome}/google/${name}/google_token.json";
            grantsSend = builtins.any google.grantsSend acct.capabilities;
        }) accounts;
    };

    manifest = pkgs.writeText "hermes-google-accounts-${agent}.json"
        (builtins.toJSON manifestData);

    # Funtion to create a wrapper that executes google_accounts.py for a given verb with the manifest as an input
    script = pkgs.copyPathToStore ./google_accounts.py;
    runner = verb: ''
        export HERMES_GOOGLE_MANIFEST=${manifest}
        exec ${googlePython}/bin/python3 ${script} ${verb} "$@"
    '';

    mkWrapper = name: { verb, description }: pkgs.writeShellApplication {
        inherit name;
        runtimeInputs = [ ];
        meta.description = description;
        text = ''
            # Generated by hermes/google/wrappers.nix for agent '${agent}'.
            # Do not edit: a nixos-rebuild overwrites it. Change
            # hermes/users/${agent}.nix instead.
            ${runner verb}
        '';
    };

    authWrapper = mkWrapper "hermes-google-auth" {
        verb = "auth";
        description = "One-time Google OAuth consent for a declared account";
    };

    statusWrapper = mkWrapper "hermes-google-status" {
        verb = "status";
        description = "Declared vs granted Google access for every declared account";
    };


    # Wrapper for gmail with better account handling
    gmailWrapper = pkgs.writeShellApplication {
        name = "hermes-gmail";
        runtimeInputs = [ ];
        meta.description = "Gmail (and the rest of google_api.py) for a declared account";
        text = ''
            # Generated by hermes/google/wrappers.nix for agent '${agent}'.
            if [ "''${1:-}" != "--account" ] || [ "$#" -lt 2 ]; then
                echo "usage: hermes-gmail --account <name> <service> <subcommand> [args...]" >&2
                echo "  e.g. hermes-gmail --account agent gmail search 'is:unread' --max 5" >&2
                echo "  declared accounts: ${lib.concatStringsSep " " (lib.attrNames accounts)}" >&2
                echo "  consult 'hermes-google-status' to see what each one may do and ensure that you don't overstep boundaries " >&2
                exit 2
            fi
            account="$2"
            shift 2
            export HERMES_GOOGLE_MANIFEST=${manifest}
            exec ${googlePython}/bin/python3 ${script} api "$account" "$@"
        '';
    };


    # Wrapper for all Google api uses
    perAccountWrappers = lib.mapAttrsToList (name: acct:
        let
            usage = pkgs.writeText "hermes-google-${name}-usage" ''
                usage: hermes-google-${name} <service> <subcommand> [args...]

                  e.g. hermes-google-${name} gmail search 'is:unread' --max 5
                       hermes-google-${name} calendar list

                capabilities (baked in at build time -- change them in
                hermes/users/${agent}.nix, then re-run hermes-google-auth ${name}):
                ${lib.concatMapStringsSep "\n" (c: "  ${c}") acct.capabilities}

                purpose:
                ${lib.concatMapStringsSep "\n" (l: "  ${l}") (lib.splitString "\n" acct.purpose)}

                Run `hermes-google-status ${name}` for live token state.
            '';
        in pkgs.writeShellApplication {
            name = "hermes-google-${name}";
            runtimeInputs = [ pkgs.coreutils ];
            meta.description = "Google API as the '${name}' account (${lib.concatStringsSep " " acct.capabilities})";
            text = ''
                if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
                    cat ${usage} >&2
                    exit 2
                fi
                export HERMES_GOOGLE_MANIFEST=${manifest}
                exec ${googlePython}/bin/python3 ${script} api ${lib.escapeShellArg name} "$@"
            '';
        }
    ) accounts;

    skillsDir = (import ../lib.nix {
        inherit pkgs lib;
        config = null;
    }).skills.google-oauth;
in
{
    inherit manifest skillsDir;
    manifestData = manifestData;

    packages = [ authWrapper statusWrapper gmailWrapper ] ++ perAccountWrappers;
}
