"""
Model gateway.

One OpenAI-compatible endpoint in front of every inference server you run, so
agents get a single base URL and a single catalogue instead of a hand-maintained
map of ports.

The gateway never guesses what a backend can serve.  It asks:

  * discovery = "probe"   -- GET {url}/v1/models on a timer, take the ids
                             verbatim.  This is how llama.cpp servers are
                             handled: change `--alias` over there and the
                             catalogue here follows on the next refresh.

  * discovery = "static"  -- the ids are declared in the Nix config, and the
                             only thing polled is a cheap liveness path.  This
                             mode exists for exactly one reason: the wake-on-LAN
                             proxy on :8090 answers /v1/models through its
                             catch-all route, which calls ensure_inference_ready()
                             and *boots the PC*.  Probing that endpoint every
                             minute would keep a sleeping machine awake forever
                             and defeat the entire design.  So we hit
                             /proxy/status instead -- the one route registered
                             ahead of the catch-all -- and read the state machine
                             without touching the hardware.

A static endpoint that reports `served_model` while it happens to be awake gets
that id folded into the table too, so a mislabelled declaration self-corrects the
first time the machine is up.

Configuration is generated by model-gateway.nix into CONFIG_PATH.  Nix owns the
topology; this file owns the behaviour.
"""

import asyncio, json, time
from dataclasses import dataclass, field

import httpx
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import StreamingResponse


CONFIG_PATH = '/etc/model-gateway/config.json'


# --------------------------------------------------------------------------- #
#  Config / state
# --------------------------------------------------------------------------- #

@dataclass
class Endpoint:
    name: str
    url: str
    discovery: str            # 'probe' | 'static'
    models: list[str]         # declared ids; only consulted when static
    prefix: str | None        # exposed as f'{prefix}{id}', stripped on forward
    health_path: str | None
    priority: int             # higher wins a collision on the same exposed id
    timeout: float            # read timeout for *forwarded* traffic, seconds

    # Runtime, refreshed by the probe loop.
    ok: bool = False
    detail: str = 'not probed yet'
    last_probe: float = 0.0
    upstream_state: str | None = None
    discovered: list[str] = field(default_factory=list)

    def exposed(self, upstream_id: str) -> str:
        return f'{self.prefix}{upstream_id}' if self.prefix else upstream_id


CONFIG: dict = {}
ENDPOINTS: list[Endpoint] = []

# exposed model id -> (endpoint, id to send upstream)
ROUTES: dict[str, tuple[Endpoint, str]] = {}

CLIENT: httpx.AsyncClient | None = None


def load_config() -> None:
    global CONFIG, ENDPOINTS

    with open(CONFIG_PATH) as fh:
        CONFIG = json.load(fh)

    ENDPOINTS = [
        Endpoint(
            name=e['name'],
            url=e['url'].rstrip('/'),
            discovery=e.get('discovery', 'probe'),
            models=e.get('models', []),
            prefix=e.get('prefix') or None,
            health_path=e.get('health_path') or None,
            priority=e.get('priority', 100),
            timeout=float(e.get('timeout', 600.0)),
        )
        for e in CONFIG['endpoints']
    ]


# --------------------------------------------------------------------------- #
#  Discovery
# --------------------------------------------------------------------------- #

async def probe_endpoint(ep: Endpoint) -> None:
    probe_timeout = CONFIG.get('probe_timeout', 5.0)
    ep.last_probe = time.time()

    if ep.discovery == 'probe':
        try:
            resp = await CLIENT.get(f'{ep.url}/v1/models', timeout=probe_timeout)
        except Exception as exc:
            ep.ok, ep.detail = False, f'{type(exc).__name__}: {exc}'
            ep.discovered = []
            return

        if resp.status_code != 200:
            ep.ok, ep.detail = False, f'HTTP {resp.status_code} from /v1/models'
            ep.discovered = []
            return

        try:
            data = resp.json().get('data', [])
        except Exception as exc:
            ep.ok, ep.detail = False, f'unparseable /v1/models: {exc}'
            ep.discovered = []
            return

        ep.discovered = [m['id'] for m in data if isinstance(m, dict) and m.get('id')]
        ep.ok = True
        ep.detail = f'{len(ep.discovered)} model(s)'
        return

    # ---- static -----------------------------------------------------------
    # Declared ids stay in the table whether or not the backend is up.  That is
    # deliberate: an agent enumerating /v1/models needs to see the sleeping
    # machine's model, otherwise it can never send the request that wakes it.
    ids = list(ep.models)

    if ep.health_path is None:
        ep.ok, ep.detail = True, 'declared (no liveness path configured)'
    else:
        try:
            resp = await CLIENT.get(f'{ep.url}{ep.health_path}', timeout=probe_timeout)
            if resp.status_code == 200:
                ep.ok = True
                try:
                    body = resp.json()
                except Exception:
                    body = {}
                ep.upstream_state = body.get('pc_state')
                served = body.get('served_model')
                if served and served not in ids:
                    # The backend told us what it is actually holding; trust that
                    # over the declaration.
                    ids.append(served)
                ep.detail = f'reachable (state={ep.upstream_state or "?"})'
            else:
                ep.ok, ep.detail = False, f'HTTP {resp.status_code} from {ep.health_path}'
        except Exception as exc:
            ep.ok, ep.detail = False, f'{type(exc).__name__}: {exc}'

    ep.discovered = ids


def rebuild_routes() -> None:
    global ROUTES

    table: dict[str, tuple[Endpoint, str]] = {}

    # Descending priority, then name for a stable tie-break, so the first writer
    # of a given id wins and the loser is the one we report.
    for ep in sorted(ENDPOINTS, key=lambda e: (-e.priority, e.name)):
        for upstream in ep.discovered:
            exposed = ep.exposed(upstream)
            if exposed in table:
                winner = table[exposed][0]
                if winner is not ep:
                    print(
                        f'[ROUTE] collision on "{exposed}": serving it from '
                        f'"{winner.name}" (priority {winner.priority}), ignoring '
                        f'"{ep.name}" (priority {ep.priority}).  Set a `prefix` '
                        f'on one of them to expose both.'
                    )
                continue
            table[exposed] = (ep, upstream)

    ROUTES = table


async def refresh_loop() -> None:
    interval = CONFIG.get('refresh_seconds', 60)
    while True:
        # Probes run concurrently: one unreachable backend must not add its
        # timeout to everyone else's refresh latency.
        await asyncio.gather(*(probe_endpoint(ep) for ep in ENDPOINTS))
        before = set(ROUTES)
        rebuild_routes()
        if set(ROUTES) != before:
            print(f'[CATALOGUE] {len(ROUTES)} model(s): {", ".join(sorted(ROUTES))}')
        await asyncio.sleep(interval)


# --------------------------------------------------------------------------- #
#  App
# --------------------------------------------------------------------------- #

async def lifespan(app: FastAPI):
    global CLIENT

    load_config()
    print(f'[SERVICE] Starting model-gateway with {len(ENDPOINTS)} endpoint(s)')

    CLIENT = httpx.AsyncClient(
        limits=httpx.Limits(max_connections=32, max_keepalive_connections=8),
        # Per-request read timeouts are set at forward time from the endpoint's
        # own budget; this is only the floor.  connect stays short so a dead
        # backend fails fast instead of hanging the caller.
        timeout=httpx.Timeout(connect=5.0, read=600.0, write=60.0, pool=10.0),
        follow_redirects=False,
    )

    # Probe once before accepting traffic, so the first /v1/models is not empty.
    await asyncio.gather(*(probe_endpoint(ep) for ep in ENDPOINTS))
    rebuild_routes()
    print(f'[CATALOGUE] {len(ROUTES)} model(s): {", ".join(sorted(ROUTES))}')

    task = asyncio.create_task(refresh_loop())
    yield

    print('[SERVICE] Shutting down model-gateway')
    task.cancel()
    await asyncio.gather(task, return_exceptions=True)
    await CLIENT.aclose()


app = FastAPI(lifespan=lifespan)


def catalogue() -> list[dict]:
    return [
        {
            'id': exposed,
            'object': 'model',
            'created': int(ep.last_probe),
            'owned_by': ep.name,
        }
        for exposed, (ep, _) in sorted(ROUTES.items())
    ]


# All of these are registered BEFORE the catch-all: FastAPI matches in
# registration order and '/{path:path}' swallows everything after it.

@app.get('/v1/models')
@app.get('/models')
async def list_models():
    return {'object': 'list', 'data': catalogue()}


@app.get('/v1/models/{model_id:path}')
async def get_model(model_id: str):
    for entry in catalogue():
        if entry['id'] == model_id:
            return entry
    raise HTTPException(status_code=404, detail=f'No such model: "{model_id}"')


@app.get('/gateway/status')
async def gateway_status():
    """Everything the router knows, without touching a single backend.

    Safe to poll: it reads cached probe results, so hitting this never wakes a
    sleeping machine.
    """
    return {
        'endpoints': [
            {
                'name': ep.name,
                'url': ep.url,
                'discovery': ep.discovery,
                'priority': ep.priority,
                'ok': ep.ok,
                'detail': ep.detail,
                'upstream_state': ep.upstream_state,
                'models': [ep.exposed(m) for m in ep.discovered],
                'last_probe_age_seconds': int(time.time() - ep.last_probe) if ep.last_probe else None,
            }
            for ep in ENDPOINTS
        ],
        'routes': {
            exposed: {'endpoint': ep.name, 'upstream_model': upstream}
            for exposed, (ep, upstream) in sorted(ROUTES.items())
        },
    }


@app.post('/gateway/refresh')
async def gateway_refresh():
    """Force a rediscovery instead of waiting out refresh_seconds.

    Note that this DOES probe every endpoint -- but only the ones marked
    `probe`, so it still will not wake the PC.
    """
    await asyncio.gather(*(probe_endpoint(ep) for ep in ENDPOINTS))
    rebuild_routes()
    return {'models': sorted(ROUTES)}


def pick_route(body: bytes, method: str) -> tuple[Endpoint, str, str | None]:
    """Resolve (endpoint, upstream model id, requested id) from a request body.

    Both the OpenAI surfaces (/v1/chat/completions, /v1/completions,
    /v1/responses, /v1/embeddings) and the Anthropic one (/v1/messages) carry
    the model in a top-level "model" field, so one parse covers all of them.
    """
    requested = None
    if method == 'POST' and body:
        try:
            requested = json.loads(body).get('model')
        except Exception:
            requested = None

    if requested is None:
        requested = CONFIG.get('default_model')
        if requested is None:
            raise HTTPException(
                status_code=400,
                detail=(
                    'This gateway routes by model id, and the request carried '
                    'none.  Send a "model" field, or set '
                    'services.model-gateway.defaultModel in the NixOS config.'
                ),
            )

    route = ROUTES.get(requested)
    if route is None:
        raise HTTPException(
            status_code=404,
            detail={
                'message': f'No backend serves model "{requested}".',
                'available_models': sorted(ROUTES),
            },
        )

    ep, upstream = route
    return ep, upstream, requested


@app.api_route('/{path:path}', methods=['GET', 'POST', 'DELETE'])
async def route_request(request: Request, path: str):
    body = await request.body()
    ep, upstream, requested = pick_route(body, request.method)

    headers = dict(request.headers)
    headers.pop('host', None)
    # We re-read the body, so any client-supplied length is stale the moment we
    # rewrite the model field; httpx sets both of these itself.
    headers.pop('content-length', None)
    headers.pop('accept-encoding', None)

    content = body
    if requested is not None and upstream != requested and body:
        # Only happens when a `prefix` is in play: the client asked for
        # "pc/Qwen3.8-27B", the backend only answers to "Qwen3.8-27B".
        try:
            payload = json.loads(body)
            payload['model'] = upstream
            content = json.dumps(payload).encode()
        except Exception:
            pass

    req = CLIENT.build_request(
        method=request.method,
        url=f'{ep.url}/{path}',
        headers=headers,
        content=content,
        params=request.query_params,
        # The wake-on-demand endpoint blocks for the whole WoL -> boot -> load
        # sequence on a cold request, which is minutes.  A per-endpoint budget
        # keeps that from forcing the same patience on the always-on backends.
        timeout=httpx.Timeout(connect=5.0, read=ep.timeout, write=60.0, pool=10.0),
    )

    try:
        resp = await CLIENT.send(req, stream=True)
    except Exception as exc:
        raise HTTPException(
            status_code=502,
            detail=f'Backend "{ep.name}" ({ep.url}) failed: {type(exc).__name__}: {exc}',
        )

    async def body_iterator():
        try:
            async for chunk in resp.aiter_raw():
                yield chunk
        finally:
            await resp.aclose()

    response_headers = {
        k: v for k, v in resp.headers.items()
        if k.lower() not in ('content-length', 'transfer-encoding', 'connection', 'content-encoding')
    }
    # Cheap way to see which box answered, without opening /gateway/status.
    response_headers['x-gateway-endpoint'] = ep.name
    response_headers['x-gateway-model'] = upstream

    return StreamingResponse(
        body_iterator(),
        status_code=resp.status_code,
        headers=response_headers,
        media_type=resp.headers.get('content-type'),
    )


if __name__ == '__main__':
    with open(CONFIG_PATH) as fh:
        listen = json.load(fh)['listen']
    uvicorn.run(app, host=listen['host'], port=listen['port'])
